language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm

env:
  global:
    secure: UVvBxNf6tsDjCT6NFADBEpSH2Oeh5ikTh+RugVuW+gMhnF6cnapSO9YJE5RpVu8RjIPZInDiEyrFjufHvbLEdr/Zj9AMHJruDpKjxkIV9dnOre6z3pAF15DPTp5prD6xaJVyHHkLiFufR2E3QTVFSiwJNC9/LAmE8D5CIa6+RSs=

before_script:
- composer require satooshi/php-coveralls:~0.6 --dev

script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
- if [ $TRAVIS_PHP_VERSION = '5.6' ]; then sh generate-api.sh; fi

notifications:
  email: false
